spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_security_jwt?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&useUnicode=true&useLegacyDatetimeCode=false
    username: newuser
    password: supervisor888
    schema: classpath:schema.sql
    data: classpath:import.sql
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true

